/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Entity.Employee;
import javax.swing.JOptionPane;
import pharmacysystem.myprotools;

/**
 *
 * @author Ali
 */
public class frmemployee extends javax.swing.JFrame {

    /**
     * Creates new form frmemployee
     */
    public frmemployee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtName = new systemControlsComponent.JTEXTBOX(50);
        jLabel8 = new javax.swing.JLabel();
        rdID = new javax.swing.JRadioButton();
        rdName = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmployee = new javax.swing.JTable();
        txtShiftStart = new systemControlsComponent.JTEXTBOX(50);
        txtID = new systemControlsComponent.JTEXTBOX(50);
        txtShiftEnd = new systemControlsComponent.JTEXTBOX(50);
        txtPhone = new systemControlsComponent.JTEXTBOX(50);
        txtSalary = new systemControlsComponent.JTEXTBOX(50);
        btnUpdate = new systemControlsComponent.JBUTTON();
        btnAdd = new systemControlsComponent.JBUTTON();
        btnDelete = new systemControlsComponent.JBUTTON();
        btnFind = new systemControlsComponent.JBUTTON();
        btnAll = new systemControlsComponent.JBUTTON();
        btnClear = new systemControlsComponent.JBUTTON();
        btnSearch = new systemControlsComponent.JBUTTON();
        txtSearchKey = new systemControlsComponent.JTEXTBOX(50);
        btnAdd1 = new systemControlsComponent.JBUTTON();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1600, 900));
        setMinimumSize(new java.awt.Dimension(1600, 900));
        setResizable(false);
        setSize(new java.awt.Dimension(1600, 900));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Employee Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Shift Start:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Employee ID:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Shift End:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Employee Salary:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Employee Phone:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, -1, -1));

        txtName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 180, 37));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel8.setText("Search by:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, -1, -1));

        rdID.setBackground(new java.awt.Color(219, 240, 237));
        rdID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rdID.setSelected(true);
        rdID.setText("ID");
        rdID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdIDActionPerformed(evt);
            }
        });
        getContentPane().add(rdID, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 70, -1, -1));

        rdName.setBackground(new java.awt.Color(219, 240, 237));
        rdName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rdName.setText("Name");
        rdName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdNameActionPerformed(evt);
            }
        });
        getContentPane().add(rdName, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 70, -1, -1));

        tblEmployee.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Start", "End", "Phone", "Salary"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmployeeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEmployee);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 200, 739, 484));

        txtShiftStart.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtShiftStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtShiftStartActionPerformed(evt);
            }
        });
        getContentPane().add(txtShiftStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 180, 37));

        txtID.setEditable(false);
        txtID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 180, 37));

        txtShiftEnd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtShiftEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtShiftEndActionPerformed(evt);
            }
        });
        getContentPane().add(txtShiftEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 180, 37));

        txtPhone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });
        getContentPane().add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 180, 37));

        txtSalary.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalaryActionPerformed(evt);
            }
        });
        getContentPane().add(txtSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, 180, 37));

        btnUpdate.setText("Update");
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, 110, 40));

        btnAdd.setText("Add");
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 480, 80, 40));

        btnDelete.setText("Delete");
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 480, 110, 40));

        btnFind.setText("Find");
        btnFind.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });
        getContentPane().add(btnFind, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 570, 80, 40));

        btnAll.setText("All");
        btnAll.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAllMouseClicked(evt);
            }
        });
        btnAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllActionPerformed(evt);
            }
        });
        getContentPane().add(btnAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 570, 110, 40));

        btnClear.setText("Clear");
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 570, 110, 40));

        btnSearch.setText("Search");
        btnSearch.setFocusable(false);
        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(897, 120, 120, -1));

        txtSearchKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchKeyActionPerformed(evt);
            }
        });
        getContentPane().add(txtSearchKey, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 120, 190, 37));

        btnAdd1.setText("Back");
        btnAdd1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 640, 80, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon("D:\\courses\\Paharmacy project\\Design Phase\\emp.jpg")); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void rdIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdIDActionPerformed

    private void rdNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdNameActionPerformed

    private void txtShiftStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtShiftStartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtShiftStartActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtShiftEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtShiftEndActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtShiftEndActionPerformed

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void txtSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalaryActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        setValues();
        emp.update();
        clearData();
        emp.getAllRows(tblEmployee);
    }//GEN-LAST:event_btnUpdateActionPerformed
    private void setValues() {
        emp.setEmpID(Integer.parseInt(txtID.getText()));
        emp.setEmpName(txtName.getText());
        emp.setShiftStart(txtShiftStart.getText());
        emp.setShiftEnd(txtShiftEnd.getText());
        emp.setEmpPhone(txtPhone.getText());
        emp.setEmpSalary(Double.parseDouble(txtSalary.getText()));
    }
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        setValues();
        emp.add();
        clearData();
        emp.getAllRows(tblEmployee);
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtSearchKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchKeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchKeyActionPerformed
    Employee emp = new Employee();

    private void clearData() {
        myprotools.cleartxt(this);
        txtID.setText(emp.getAutoNumber());
        btnAdd.setEnabled(true);
        btnDelete.setEnabled(false);
        btnUpdate.setEnabled(false);
        txtName.requestFocus();
    }
    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearData();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        setValues();
        emp.delete();
        clearData();
        emp.getAllRows(tblEmployee);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd1ActionPerformed
        this.dispose();
        myprotools.setOpenForm(new frmMain(),"Main Form");
    }//GEN-LAST:event_btnAdd1ActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        String findKey = (String) myprotools.inputBox("");
        emp.setEmpID(Integer.parseInt(findKey));
        emp.getOneRow(tblEmployee);
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllActionPerformed
        emp.getAllRows(tblEmployee);
    }//GEN-LAST:event_btnAllActionPerformed

    private void btnAllMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAllMouseClicked

    }//GEN-LAST:event_btnAllMouseClicked

    private void tblEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmployeeMouseClicked
        try {
            int row = tblEmployee.getSelectedRow();
            String strID = tblEmployee.getValueAt(row, 0).toString();
            String strName = tblEmployee.getValueAt(row, 1).toString();
            String strStart = tblEmployee.getValueAt(row, 2).toString();
            String strEnd = tblEmployee.getValueAt(row, 3).toString();
            String strPhone = tblEmployee.getValueAt(row, 4).toString();
            String strSalary = tblEmployee.getValueAt(row, 5).toString();

            txtID.setText(strID);
            txtName.setText(strName);
            txtShiftStart.setText(strStart);
            txtShiftEnd.setText(strEnd);
            txtPhone.setText(strPhone);
            txtSalary.setText(strSalary);

            btnAdd.setEnabled(false);
            btnDelete.setEnabled(true);
            btnUpdate.setEnabled(true);
        } catch (Exception e) {
            myprotools.msgbooks(e.getMessage());
        }
    }//GEN-LAST:event_tblEmployeeMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        clearData();
        btnGroup.add(rdID);
        btnGroup.add(rdName);
        emp.getAllRows(tblEmployee);
        txtID.setText(emp.getAutoNumber());
    }//GEN-LAST:event_formWindowOpened

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        try  {
            String strstatement = "select * from employee where";
            if (rdID.isSelected()) {
                strstatement += " empID";
            } else if (rdName.isSelected()) {
                strstatement += " empName";
            }
            strstatement += " like '%" +txtSearchKey.getText()+"%'";
            emp.getCustomRows(strstatement, tblEmployee);
        
        } catch (Exception e) {
            myprotools.msgbooks(e.getMessage());
        }

    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmemployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private systemControlsComponent.JBUTTON btnAdd;
    private systemControlsComponent.JBUTTON btnAdd1;
    private systemControlsComponent.JBUTTON btnAll;
    private systemControlsComponent.JBUTTON btnClear;
    private systemControlsComponent.JBUTTON btnDelete;
    private systemControlsComponent.JBUTTON btnFind;
    private javax.swing.ButtonGroup btnGroup;
    private systemControlsComponent.JBUTTON btnSearch;
    private systemControlsComponent.JBUTTON btnUpdate;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdID;
    private javax.swing.JRadioButton rdName;
    private javax.swing.JTable tblEmployee;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSalary;
    private javax.swing.JTextField txtSearchKey;
    private javax.swing.JTextField txtShiftEnd;
    private javax.swing.JTextField txtShiftStart;
    // End of variables declaration//GEN-END:variables
}
