/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Entity.Drags;
import Entity.Employee;
import Entity.EmployeeSellingDrags;
import pharmacysystem.myprotools;

/**
 *
 * @author Ali
 */
public class frmEmployeeSellingDrags extends javax.swing.JFrame {

    /**
     * Creates new form frmEmployeeSellingDrags
     */
    public frmEmployeeSellingDrags() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comEmpName = new systemControlsComponent.JCOMPBOX();
        comDragName = new systemControlsComponent.JCOMPBOX();
        btnSearch = new systemControlsComponent.JBUTTON();
        btndelete = new systemControlsComponent.JBUTTON();
        btnFind = new systemControlsComponent.JBUTTON();
        btnAll = new systemControlsComponent.JBUTTON();
        jLabel4 = new javax.swing.JLabel();
        rdEmpName = new javax.swing.JRadioButton();
        rdEmpID = new javax.swing.JRadioButton();
        rdDraID = new javax.swing.JRadioButton();
        rdDraName = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmpSDraInfo = new javax.swing.JTable();
        jBUTTON5 = new systemControlsComponent.JBUTTON();
        btnAdd1 = new systemControlsComponent.JBUTTON();
        btnAdd2 = new systemControlsComponent.JBUTTON();
        btnAdd3 = new systemControlsComponent.JBUTTON();
        txtSearchKey = new systemControlsComponent.JTEXTBOX(50);
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(142, 180, 191));
        setMaximumSize(new java.awt.Dimension(1600, 900));
        setMinimumSize(new java.awt.Dimension(1600, 900));
        setPreferredSize(new java.awt.Dimension(1600, 900));
        setResizable(false);
        setSize(new java.awt.Dimension(1600, 900));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setText("Employee Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 160, 25));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel3.setText("Drag Name:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, -1));

        comEmpName.setForeground(new java.awt.Color(60, 63, 65));
        getContentPane().add(comEmpName, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 170, 37));

        comDragName.setForeground(new java.awt.Color(60, 63, 65));
        getContentPane().add(comDragName, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 170, 37));

        btnSearch.setBackground(new java.awt.Color(142, 180, 191));
        btnSearch.setText("Search");
        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 160, 100, 40));

        btndelete.setText("Delete");
        btndelete.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 104, 40));

        btnFind.setText("Find");
        btnFind.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });
        getContentPane().add(btnFind, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 114, 40));

        btnAll.setText("All");
        btnAll.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllActionPerformed(evt);
            }
        });
        getContentPane().add(btnAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, 70, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel4.setText("Search by:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 70, -1, -1));

        rdEmpName.setBackground(new java.awt.Color(219, 240, 237));
        rdEmpName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rdEmpName.setSelected(true);
        rdEmpName.setText("Employee Name");
        getContentPane().add(rdEmpName, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 70, -1, -1));

        rdEmpID.setBackground(new java.awt.Color(219, 240, 237));
        rdEmpID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rdEmpID.setText("Employee ID");
        getContentPane().add(rdEmpID, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 70, -1, -1));

        rdDraID.setBackground(new java.awt.Color(219, 240, 237));
        rdDraID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rdDraID.setText("Drag ID");
        getContentPane().add(rdDraID, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 170, -1, 28));

        rdDraName.setBackground(new java.awt.Color(219, 240, 237));
        rdDraName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rdDraName.setText("Drag Name");
        getContentPane().add(rdDraName, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 70, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(111, 196, 152));
        jScrollPane1.setForeground(new java.awt.Color(0, 0, 0));

        tblEmpSDraInfo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tblEmpSDraInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee ID", "Employee Name", "Drag ID", "Drag Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEmpSDraInfo.setCellSelectionEnabled(true);
        tblEmpSDraInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblEmpSDraInfo.setInheritsPopupMenu(true);
        tblEmpSDraInfo.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jScrollPane1.setViewportView(tblEmpSDraInfo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 280, 618, 398));

        jBUTTON5.setText("Back");
        jBUTTON5.setToolTipText("");
        jBUTTON5.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jBUTTON5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBUTTON5ActionPerformed(evt);
            }
        });
        getContentPane().add(jBUTTON5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 640, 84, 40));

        btnAdd1.setText("+");
        btnAdd1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 70, 37));

        btnAdd2.setText("+");
        btnAdd2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAdd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 70, 40));

        btnAdd3.setText("Add");
        btnAdd3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnAdd3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 84, 40));

        txtSearchKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchKeyActionPerformed(evt);
            }
        });
        getContentPane().add(txtSearchKey, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 160, 139, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\courses\\Paharmacy project\\Design Phase\\Selling4.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -90, 1600, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBUTTON5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBUTTON5ActionPerformed
        this.dispose();
        myprotools.setOpenForm(new frmMain(),"Main Form");
    }//GEN-LAST:event_jBUTTON5ActionPerformed
    EmployeeSellingDrags e=new EmployeeSellingDrags();
    private void setValues(){
     e.setid(Integer.parseInt(e.getAutoNumber()));
     String empname=comEmpName.getSelectedItem().toString();
     String draname=comDragName.getSelectedItem().toString();
     e.setEmpID(Integer.parseInt(new Employee().getValueByName(empname)));
     e.setDraID(Integer.parseInt(new Drags().getValueByName(draname)));
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        db.go.fillCompoBox("employee", "empName", comEmpName);
        db.go.fillCompoBox("drug", "drugName", comDragName);
        btnGroup.add(rdEmpID);
        btnGroup.add(rdEmpName);
        btnGroup.add(rdDraID);
        btnGroup.add(rdDraName);
        e.getAllRows(tblEmpSDraInfo);
    }//GEN-LAST:event_formWindowOpened

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String statement="select *from sellingDrugs where ";
        if(rdDraID.isSelected()){
            statement+="drugId";
        }else if(rdDraName.isSelected()){
            statement+="DrugName";
        }else if(rdEmpID.isSelected()){
            statement+="employeeId";
        }else if(rdEmpName.isSelected()){
            statement+="employeeName";
        }
        statement+=" like'%"+txtSearchKey.getText()+"%'";
        e.getCustomRows(statement, tblEmpSDraInfo);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        setValues();
        e.delete();
        e.getAllRows(tblEmpSDraInfo);
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        int id=Integer.parseInt(myprotools.inputBox("Enter employee ID").toString());
        e.getCustomRows("select *from sellingDrugs where employeeId="+id, tblEmpSDraInfo);
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllActionPerformed
        e.getAllRows(tblEmpSDraInfo);
    }//GEN-LAST:event_btnAllActionPerformed

    private void btnAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd1ActionPerformed
        this.dispose();
        myprotools.setOpenForm(new frmemployee(),"Main Form/Employee Form");
    }//GEN-LAST:event_btnAdd1ActionPerformed

    private void btnAdd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd2ActionPerformed
        this.dispose();
        myprotools.setOpenForm(new frmDrags(),"Main Form/Drags Form");
    }//GEN-LAST:event_btnAdd2ActionPerformed

    private void btnAdd3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd3ActionPerformed
        setValues();
        e.add();
        e.getAllRows(tblEmpSDraInfo);
    }//GEN-LAST:event_btnAdd3ActionPerformed

    private void txtSearchKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchKeyActionPerformed
        String statement="select *from sellingDrugs where ";
        if(rdEmpID.isSelected()){
            statement+="employeeId";
        }else if(rdEmpName.isSelected()){
            statement+="emploteeName";
        }else if(rdDraID.isSelected()){
            statement+="drugId";
        }else if(rdDraName.isSelected()){
            statement+="dragName";
        }
        statement=" like'%"+txtSearchKey+"%'";
        e.getCustomRows(statement, tblEmpSDraInfo);
    }//GEN-LAST:event_txtSearchKeyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEmployeeSellingDrags.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEmployeeSellingDrags.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEmployeeSellingDrags.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEmployeeSellingDrags.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEmployeeSellingDrags().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private systemControlsComponent.JBUTTON btnAdd1;
    private systemControlsComponent.JBUTTON btnAdd2;
    private systemControlsComponent.JBUTTON btnAdd3;
    private systemControlsComponent.JBUTTON btnAll;
    private systemControlsComponent.JBUTTON btnFind;
    private javax.swing.ButtonGroup btnGroup;
    private systemControlsComponent.JBUTTON btnSearch;
    private systemControlsComponent.JBUTTON btndelete;
    private systemControlsComponent.JCOMPBOX comDragName;
    private systemControlsComponent.JCOMPBOX comEmpName;
    private systemControlsComponent.JBUTTON jBUTTON5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdDraID;
    private javax.swing.JRadioButton rdDraName;
    private javax.swing.JRadioButton rdEmpID;
    private javax.swing.JRadioButton rdEmpName;
    private javax.swing.JTable tblEmpSDraInfo;
    private javax.swing.JTextField txtSearchKey;
    // End of variables declaration//GEN-END:variables
}
