/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import db.go;
import pharmacysystem.myprotools;


/**
 *
 * @author Ali
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmlogin
     */
    public frmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnexit2 = new systemControlsComponent.JBUTTON();
        btnexit3 = new systemControlsComponent.JBUTTON();
        btnexit4 = new systemControlsComponent.JBUTTON();
        btnexit5 = new systemControlsComponent.JBUTTON();
        btnexit6 = new systemControlsComponent.JBUTTON();
        btnexit7 = new systemControlsComponent.JBUTTON();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1024, 798));
        setMinimumSize(new java.awt.Dimension(1024, 798));
        setPreferredSize(new java.awt.Dimension(1024, 798));
        setResizable(false);
        setSize(new java.awt.Dimension(1024, 798));
        getContentPane().setLayout(null);

        btnexit2.setText("Employee Form");
        btnexit2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnexit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexit2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnexit2);
        btnexit2.setBounds(389, 134, 216, 48);

        btnexit3.setText("EXIT");
        btnexit3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnexit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexit3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnexit3);
        btnexit3.setBounds(130, 660, 120, 38);

        btnexit4.setText("Store Form");
        btnexit4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnexit4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexit4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnexit4);
        btnexit4.setBounds(389, 241, 216, 48);

        btnexit5.setText("Drug Form");
        btnexit5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnexit5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexit5ActionPerformed(evt);
            }
        });
        getContentPane().add(btnexit5);
        btnexit5.setBounds(389, 357, 216, 48);

        btnexit6.setText("Patient Form");
        btnexit6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnexit6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexit6ActionPerformed(evt);
            }
        });
        getContentPane().add(btnexit6);
        btnexit6.setBounds(389, 464, 216, 48);

        btnexit7.setText("Selling Form");
        btnexit7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnexit7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexit7ActionPerformed(evt);
            }
        });
        getContentPane().add(btnexit7);
        btnexit7.setBounds(389, 587, 216, 48);

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\courses\\Paharmacy project\\Design Phase\\main3.jpg")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1030, 800);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnexit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexit2ActionPerformed
        this.dispose();
        myprotools.setOpenForm(new frmemployee(),"Main Form/Employee Form");   
    }//GEN-LAST:event_btnexit2ActionPerformed

    private void btnexit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexit3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnexit3ActionPerformed

    private void btnexit4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexit4ActionPerformed
        this.dispose();
        myprotools.setOpenForm(new frmStore(),"Main Form/Store Form");
    }//GEN-LAST:event_btnexit4ActionPerformed

    private void btnexit5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexit5ActionPerformed
        this.dispose();
        myprotools.setOpenForm(new frmDrags(),"Main Form/Drags Form");
    }//GEN-LAST:event_btnexit5ActionPerformed

    private void btnexit6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexit6ActionPerformed
        this.dispose();
        myprotools.setOpenForm(new frmPatient(),"Main Form/Patient Form");
    }//GEN-LAST:event_btnexit6ActionPerformed

    private void btnexit7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexit7ActionPerformed
        this.dispose();
        myprotools.setOpenForm(new frmEmployeeSellingDrags(),"Main Form/Selling Form");
    }//GEN-LAST:event_btnexit7ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private systemControlsComponent.JBUTTON btnexit2;
    private systemControlsComponent.JBUTTON btnexit3;
    private systemControlsComponent.JBUTTON btnexit4;
    private systemControlsComponent.JBUTTON btnexit5;
    private systemControlsComponent.JBUTTON btnexit6;
    private systemControlsComponent.JBUTTON btnexit7;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
